/*
Exercise 04
UNIX Processes
--------------

A binary number of size n can be easily generated by a recursive function
like the one reported in file
ex04recursive.c

Transform the recursive program into a concurrent one, replacing the
recursive procedure with the generation of an appropriate number of
*processes*.
Each process must display one binary numbers.
Binary numbers can be displayed in any order.

For example, if n=3, the function must generate and print numbers:
000, 001, 010, 011, 100, 101, 110, 111
IN ANY ORDER.
*/

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/wait.h>

void binary (int*, int, int);

int main (int argc, char **argv) {
    int n;
    int *vet;

    if (argc != 2) {
        printf("USAGE: ./a.out n\n");
        return 1;
    }

    n = atoi(argv[1]);

    vet = (int*) malloc(n * sizeof(int));
    if (vet == NULL) {
        perror("Allocation error.\n");
        return 1;
    }

    printf("Binary numbers: \n");
    binary(vet, n, 0);
   
    free(vet);

    return 0;
}

void binary (int *vet, int n, int i) {
    if (i >= n) {
        for (int j = 0; j < n; j++) {
            printf("%d", vet[j]);
        }
        printf("\n");
        return;
    }

    for (int v = 0; v < 2; v++) {
        if (fork() == 0) {
            vet[i] = v;
            binary(vet, n, i + 1);
            exit(1);
        }
    }

    wait(NULL); 
    wait(NULL);
}

